version: "3.9"
services:
  postgres:
    image: "postgres:14"
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - "./.postgres_data:/var/lib/postgresql/data"
