on:
  - 'push'

jobs:
  lint-and-test:
    runs-on: 'ubuntu-latest'
    name: 'Lint and test'
    container:
      image: 'klasa/fuel-map-backend-base:latest'
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v3'
      - uses: 'actions/cache@v3'
        with:
          path: |
            /root/.cargo/bin
            /root/.cargo/registry/index/
            /root/.cargo/registry/cache/
            /root/.cargo/git/db/
            target/
          key: "${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}"
      - name: 'Check format with rustfmt'
        run: 'cargo fmt --check'
      - name: 'Test'
        run: 'cargo test'
